from typing import (
    Union, Tuple, List, Dict, Optional, Callable, Generic, TypeVar, ClassVar, Self, Any
)
from collections import defaultdict

VID = int

T = TypeVar("T", default=Any)
T1 = TypeVar("T1", default=Any)

class Value:
    value: Any
    vid: VID
    def __init__(self, value: Any) -> None: ...

class Canvas(defaultdict[int, Value]): 
    recent: ClassVar[Optional[Self]] = None
    def __init__(self, thread_safe: bool = False) -> None: ...
    @property
    def symbols(self) -> List["Symbol"]: ...
    def create_value(self, value: Any) -> VID: ...
    def get_name(self, vid: VID) -> Optional[str]: ...
    def find_symbol(self, name: str) -> VID: ...
    def get_symbol(self, vid: VID) -> Optional["Symbol"]: ...
    def clear_symbols(self) -> None: ...

class Traceable: 
    name: str
    op: str
    left: Any
    right: Any
    def __init__(self, func: Callable[[], Any], name: str, op: str = "CONST",
                 left: Any = None, right: Any = None) -> None: ...
    def __call__(self) -> Any: ...
    def calculate(self) -> Any: ...
    @staticmethod
    def wrap(other: Any) -> Self: ...
    @staticmethod
    def parse(expr: Union[str, Traceable, Expression, Any], canvas: Optional[Canvas] = None) -> Traceable: ...
    def diff(self, var: str) -> Self: ...
    def integrate(self, var_object: Any) -> Self: ...
    def get_degree(self, var: str) -> int: ...
    def get_coefficients(self, var_name: str) -> List[float]: ...
    def simplify(self) -> Self: ...
    @classmethod
    def sin(cls, expr: Any) -> Self: ...
    @classmethod
    def cos(cls, expr: Any) -> Self: ...
    @classmethod
    def tan(cls, expr: Any) -> Self: ...
    @classmethod
    def log(cls, expr: Any, base: int = ...) -> Self: ...
    @classmethod
    def exp(cls, expr: Any) -> Self: ...
    @classmethod
    def sqrt(cls, expr: Any) -> Self: ...
    @classmethod
    def conjugate(cls, expr: Any) -> Self: ...
    @classmethod
    def abs(cls, expr: Any) -> Self: ...
    @property
    def real(self) -> float: ...
    @property
    def imag(self) -> float: ...
    def __add__(self, other: Union[Self, Any]) -> Self: ...
    def __radd__(self, other: Union[Self, Any]) -> Self: ...
    def __mul__(self, other: Union[Self, Any]) -> Self: ...
    def __rmul__(self, other: Union[Self, Any]) -> Self: ...
    def __sub__(self, other: Union[Self, Any]) -> Self: ...
    def __rsub__(self, other: Union[Self, Any]) -> Self: ...
    def __truediv__(self, other: Union[Self, Any]) -> Self: ...
    def __rtruediv__(self, other: Union[Self, Any]) -> Self: ...
    def __pow__(self, other: Union[Self, Any]) -> Self: ...
    def __rpow__(self, other: Union[Self, Any]) -> Self: ...
    def __repr__(self) -> str: ...

class Symbol(tuple[str, int]): 
    def __new__(cls, name: str, value: Any = 0, canvas: Optional[Canvas] = None) -> Self: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    @property
    def written(self) -> Optional[str]: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> Any: ...
    @value.setter
    def value(self, new_value: Any) -> None: ...
    def __add__(self, other: Self) -> Traceable: ...
    def __radd__(self, other: Self) -> Traceable: ...
    def __sub__(self, other: Self) -> Traceable: ...
    def __rsub__(self, other: Self) -> Traceable: ...
    def __mul__(self, other: Self) -> Traceable: ...
    def __rmul__(self, other: Self) -> Traceable: ...
    def __truediv__(self, other: Self) -> Traceable: ...
    def __rtruediv__(self, other: Self) -> Traceable: ...
    def __pow__(self, other: Self) -> Traceable: ...
    def __rpow__(self, other: Self) -> Traceable: ...
    def create_reference(self) -> "Reference": ...

class Reference: 
    name: Optional[str]
    object: Optional[Value]
    value: Any
    def __init__(self, name: Optional[str], object: Union[Value, Any]) -> None: ...
    @property
    def vid(self) -> Optional[VID]: ...

class Expression(Generic[T1]):
    callable: Union[Callable[[], T1], Traceable]
    def __init__(self, func: Union[Callable[[], T1], Traceable], canvas: Optional[Canvas] = None) -> None: ...
    @property
    def written(self) -> Optional[str]: ...
    def calculate(self) -> T1: ...
    def __call__(self) -> T1: ...

SymbolLike = Union[str, Symbol, Reference, VID]

def get_symbol(canvas: Canvas, symbol_like: SymbolLike) -> Optional[Symbol]: ...

class Function(Generic[T, T1], Expression[T1]): 
    symbol: Symbol
    def __init__(self, symbol: SymbolLike, func: Union[Callable[[], T1], Traceable], canvas: Optional[Canvas] = None) -> None: ...
    @property
    def name(self) -> Optional[str]: ...
    def calculate(self, value: T) -> T1: ...
    def __call__(self, value: T) -> T1: ...
    def derivative(self, value: float, h: float = 1e-5) -> float: ...
    def integral(self, start: float, end: float, steps: int = 1000) -> float: ...
    def get_derivative(self) -> Self: ...
    def get_integral(self) -> Self: ...

Point = Tuple[float, float]
Points = List[Point]

Number = Union[float, complex]

class Matrix:
    data: List[List[Number]]
    rows: int
    cols: int
    def __init__(self, data: List[List[Number]]) -> None: ...
    @classmethod
    def zeros(cls, rows: int, cols: int) -> "Matrix": ...
    @classmethod
    def identity(cls, n: int) -> "Matrix": ...
    def __mul__(self, other: Union["Matrix", float]) -> "Matrix": ...
    def transpose(self) -> "Matrix": ...
    def inverse(self) -> "Matrix": ...
    def det(self) -> float: ...
    def solve(self, B: "Matrix") -> "Matrix": ...

def calculate_r_squared(points: Points, model_func: Callable[[float], float]) -> float: ...

class RegressionLin:
    points: Points
    def __init__(self, points: Points) -> None: ...
    def __call__(self) -> Tuple[float, float]: ...
    def calculate(self) -> Tuple[float, float]: ...
    def r_squared(self) -> float: ...
    def create_function(self, symbol: SymbolLike, canvas: Optional[Canvas] = None) -> Function[float, float]: ...

class RegressionPoly:
    points: Points
    degree: int
    def __init__(self, points: Points, degree: int = 2) -> None: ...
    def __call__(self) -> List[float]: ...
    def calculate(self) -> Tuple[float, float]: ...
    def r_squared(self) -> float: ...
    def create_function(self, symbol: SymbolLike, canvas: Optional[Canvas] = None) -> Function[float, float]: ...

class RegressionExp:
    points: Points
    def __init__(self, points: Points) -> None: ...
    def __call__(self) -> Tuple[float, float]: ...
    def calculate(self) -> Tuple[float, float]: ...
    def r_squared(self) -> float: ...
    def create_function(self, symbol: SymbolLike, canvas: Optional[Canvas] = None) -> Function[float, float]: ...

class RegressionLog:
    points: Points
    def __init__(self, points: Points) -> None: ...
    def __call__(self) -> Tuple[float, float]: ...
    def calculate(self) -> Tuple[float, float]: ...
    def r_squared(self) -> float: ...
    def create_function(self, symbol: SymbolLike, canvas: Optional[Canvas] = None) -> Function[float, float]: ...

class RegressionPower:
    points: Points
    def __init__(self, points: Points) -> None: ...
    def __call__(self) -> Tuple[float, float]: ...
    def calculate(self) -> Tuple[float, float]: ...
    def r_squared(self) -> float: ...
    def create_function(self, symbol: SymbolLike, canvas: Optional[Canvas] = None) -> Function[float, float]: ...

class RegressionMultiple:
    data_points: List[Tuple[List[float], float]]
    num_vars: int
    def __init__(self, data_points: List[Tuple[List[float], float]]) -> None: ...
    def __call__(self) -> List[float]: ...
    def calculate(self) -> Tuple[float, float]: ...
    def r_squared(self) -> float: ...
    def create_function(self, symbols: List[Symbol], canvas: Optional[Canvas] = None) -> Function[float, float]: ...

class Solver:
    @staticmethod
    def get_auto_range(expr: Traceable, symbol: Symbol) -> Tuple[float, float]: ...
    @staticmethod
    def solve(expr: Union[Expression, Function, Traceable, SymbolLike], 
              target: float, 
              symbol: Symbol, 
              guess: float = 1.0, 
              tol: float = 1e-7, 
              max_iter: int = 100,
              canvas: Optional[Canvas] = None) -> float: ...
    @staticmethod
    def find_extrema(expr: Union[Traceable, Function, SymbolLike], 
                     symbol: Symbol, 
                     search_range: Optional[Tuple[float, float]] = None) -> List[float]: ...
    @staticmethod
    def solve_all(expr: Union[Traceable, Function, SymbolLike], 
                  target: float, 
                  symbol: Symbol, 
                  search_range: Optional[Tuple[float, float]] = None) -> List[float]: ...
    
    @staticmethod
    def solve_complex(expr: Union[Traceable, Function, SymbolLike], 
                      target: float, 
                      symbol: Symbol, 
                      guess: Union[float, complex] = 1+1j,
                      tol: float = 1e-10, 
                      max_iter: int = 100) -> complex: ...

def fix_symbol_list(symbols: List[SymbolLike], canvas: Optional[Canvas] = None) -> List[Symbol]: ...

class SystemSolver:
    @staticmethod
    def solve_linear(equations: List[Traceable], symbols: List[Symbol]) -> Dict[str, float]: ...
    @staticmethod
    def solve_nonlinear(equations: List[Traceable], symbols: List[Symbol], 
                        guesses: List[float], max_iter: int = 50, tol: float = 1e-7) -> Dict[str, float]: ...

class Equation:
    left: Traceable
    right: Traceable
    def __init__(self, left: Any, right: Any) -> None: ...
    @staticmethod
    def parse(expr: Union[str, Equation], canvas: Optional[Canvas] = None) -> Equation: ...
    def to_zero(self) -> Traceable: ...
    def solve(self, symbol: Symbol, guess: float = 1.0) -> float: ...
    def solve_all(self, symbol: Symbol) -> List[float]: ...
    def are_equal(self) -> bool: ...
    def difference(self) -> float: ...

def parse(expr: Union[str, Traceable, Symbol, Expression, Equation, Any], canvas: Optional[Canvas] = None) -> Union[Traceable, Equation]: ...